/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "logger.h"


int
logger_1(char *host, char* uName, char* op, char* file)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	struct log_strct log_1_arg1;

	clnt = clnt_create (host, LOGGER, LOGGERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (-1);
	}

	strcpy(log_1_arg1.uName, uName);
	strcpy(log_1_arg1.op, op);
	strcpy(log_1_arg1.file, file);
	
	retval_1 = log_1(log_1_arg1, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	clnt_destroy (clnt);
	return result_1;
}


int
main (int argc, char *argv[])
{
	char *host;
	int ret;

	host = getenv("LOG_RPC_IP");
	if (host) {
		printf("usage: env LOG_RPC_IP=localhost %s\n", argv[0]);
	}

	logger_1(host, "user-1", "SEND",       "");
	logger_1(host, "user-1", "SENDATTACH", "/tmp/file1.txt");

	exit (0);
}
