/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGGER_H_RPCGEN
#define _LOGGER_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct log_strct {
	char uName[256];
	char op[256];
	char file[256];
};
typedef struct log_strct log_strct;

#define LOGGER 1
#define LOGGERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define log 1
extern  enum clnt_stat log_1(struct log_strct , int *, CLIENT *);
extern  bool_t log_1_svc(struct log_strct , int *, struct svc_req *);
extern int logger_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define log 1
extern  enum clnt_stat log_1();
extern  bool_t log_1_svc();
extern int logger_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_strct (XDR *, log_strct*);

#else /* K&R C */
extern bool_t xdr_log_strct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGGER_H_RPCGEN */
