/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "logger.h"
#include <stdbool.h>

bool_t
log_1_svc(struct log_strct arg1, int *result,  struct svc_req *rqstp)
{

	if (strcmp(arg1.op, "SENDATTACH") == 0) printf("%s %s %s\n", arg1.uName, arg1.op, arg1.file);
	else printf("%s %s %s\n", arg1.uName, arg1.op, "");
	*result = 1;
	
	return true;
}

int
logger_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);
	return 1;
}
